import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const dummyContacts = [
  {
    email: "john.doe@example.com", firstName: "John", lastName: "Doe",
    tags: '["subscriber","premium"]',
    properties: JSON.stringify({
      phone: "+1-555-0101", birthday: "1990-05-15", gender: "Male", occupation: "Software Engineer",
      language: "en", timezone: "America/New_York", country: "United States",
      website: "https://johndoe.dev", linkedin: "https://linkedin.com/in/johndoe",
      facebook: "", twitter: "", browser: "Chrome", device: "Desktop",
      contactSource: "website", jobTitle: "Senior Developer", department: "Engineering",
      annualIncome: 120000, annualRevenue: 0, customerLifetimeValue: 450,
      teamSize: 0, nps_score: 9,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_activated", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 3, total_spent: 297, average_order_value: 99,
      first_purchase_date: "2025-06-10T10:00:00Z", last_purchase_date: "2025-12-20T14:30:00Z",
      mrr: 9.99, subscription_activated_date: "2025-06-10T10:00:00Z",
      subscription_created_date: "2025-06-10T10:00:00Z",
      subscription_cancelled_date: "", trial_start_date: "2025-06-01T00:00:00Z",
      trial_end_date: "2025-06-10T00:00:00Z", next_billing_date: "2026-04-10T10:00:00Z",
      lastActivityDate: "2026-03-10T08:30:00Z",
      address: { line1: "123 Main St", line2: "Apt 4B", city: "New York", state: "NY", country: "US", zipcode: "10001" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "jane.smith@example.com", firstName: "Jane", lastName: "Smith",
    tags: '["subscriber"]',
    properties: JSON.stringify({
      phone: "+1-555-0102", birthday: "1988-11-22", gender: "Female", occupation: "Designer",
      language: "en", timezone: "America/Los_Angeles", country: "United States",
      website: "https://janesmith.design", linkedin: "", facebook: "", twitter: "",
      browser: "Safari", device: "MacBook",
      contactSource: "api", jobTitle: "UI/UX Lead", department: "Design",
      annualIncome: 95000, annualRevenue: 0, customerLifetimeValue: 199,
      teamSize: 0, nps_score: 8,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_installed", plugin_id: "starter-templates",
      plugin_name: "starter-templates", product_name: "Starter Templates",
      platform: "wordpress",
      orders_count: 1, total_spent: 49, average_order_value: 49,
      first_purchase_date: "2025-09-15T08:00:00Z", last_purchase_date: "2025-09-15T08:00:00Z",
      mrr: 0, subscription_activated_date: "", subscription_created_date: "",
      subscription_cancelled_date: "", trial_start_date: "", trial_end_date: "",
      next_billing_date: "", lastActivityDate: "2026-03-08T12:00:00Z",
      address: { line1: "456 Oak Ave", city: "San Francisco", state: "CA", country: "US", zipcode: "94102" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "alice.johnson@example.com", firstName: "Alice", lastName: "Johnson",
    tags: '["lead","trial"]',
    properties: JSON.stringify({
      phone: "+44-20-7946-0958", birthday: "", gender: "Female", occupation: "Marketing Manager",
      language: "en", timezone: "Europe/London", country: "United Kingdom",
      website: "", linkedin: "https://linkedin.com/in/alicejohnson", facebook: "", twitter: "",
      browser: "Firefox", device: "Desktop",
      contactSource: "form", jobTitle: "Marketing Manager", department: "Marketing",
      annualIncome: 0, annualRevenue: 500000, customerLifetimeValue: 0,
      teamSize: 12, nps_score: 0,
      is_marketing_allowed: "true", is_verified: "false",
      email_status: "active", email_verification_status: "pending",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "trial_started", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 0, total_spent: 0, average_order_value: 0,
      first_purchase_date: "", last_purchase_date: "",
      mrr: 0, subscription_activated_date: "",
      subscription_created_date: "", subscription_cancelled_date: "",
      trial_start_date: "2026-03-01T00:00:00Z", trial_end_date: "2026-03-15T00:00:00Z",
      next_billing_date: "", lastActivityDate: "2026-03-12T16:45:00Z",
      address: { line1: "10 Downing St", city: "London", country: "UK", zipcode: "SW1A 2AA" },
      uninstall_feedback: "switching", feedback_text: "Found a better alternative",
      feed: "", uninstall_reason_id: "reason_03",
    }),
  },
  {
    email: "bob.williams@example.com", firstName: "Bob", lastName: "Williams",
    tags: '["subscriber","enterprise"]',
    properties: JSON.stringify({
      phone: "+1-555-0104", birthday: "1982-03-08", gender: "Male", occupation: "CTO",
      language: "en", timezone: "America/Chicago", country: "United States",
      website: "https://bobwilliams.tech", linkedin: "https://linkedin.com/in/bobwilliams",
      facebook: "", twitter: "https://twitter.com/bobw",
      browser: "Chrome", device: "Desktop",
      contactSource: "api", jobTitle: "CTO", department: "Engineering",
      annualIncome: 200000, annualRevenue: 2000000, customerLifetimeValue: 2400,
      teamSize: 50, nps_score: 10,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_activated", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 12, total_spent: 1188, average_order_value: 99,
      first_purchase_date: "2025-01-20T10:00:00Z", last_purchase_date: "2026-02-15T10:00:00Z",
      mrr: 99, subscription_activated_date: "2025-01-20T10:00:00Z",
      subscription_created_date: "2025-01-20T10:00:00Z",
      subscription_cancelled_date: "", trial_start_date: "",
      trial_end_date: "", next_billing_date: "2026-04-20T10:00:00Z",
      lastActivityDate: "2026-03-14T09:15:00Z",
      address: { line1: "789 Tech Park", city: "Austin", state: "TX", country: "US", zipcode: "73301" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "charlie.brown@example.com", firstName: "Charlie", lastName: "Brown",
    tags: '["lead"]',
    properties: JSON.stringify({
      phone: "", birthday: "", gender: "Male", occupation: "Freelancer",
      language: "en", timezone: "America/Denver", country: "United States",
      website: "", linkedin: "", facebook: "", twitter: "",
      browser: "Edge", device: "Laptop",
      contactSource: "import", jobTitle: "", department: "",
      annualIncome: 0, annualRevenue: 0, customerLifetimeValue: 0,
      teamSize: 0, nps_score: 0,
      is_marketing_allowed: "false", is_verified: "false",
      email_status: "bounced", email_verification_status: "invalid",
      marketing_email_subscription_status: "unsubscribed", marketing_contact_status: "non_marketing_contact",
      event_type: "", plugin_id: "", plugin_name: "", product_name: "",
      platform: "",
      orders_count: 0, total_spent: 0, average_order_value: 0,
      first_purchase_date: "", last_purchase_date: "",
      mrr: 0, subscription_activated_date: "", subscription_created_date: "",
      subscription_cancelled_date: "", trial_start_date: "", trial_end_date: "",
      next_billing_date: "", lastActivityDate: "",
      address: {},
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "diana.prince@example.com", firstName: "Diana", lastName: "Prince",
    tags: '["subscriber","premium","early-adopter"]',
    properties: JSON.stringify({
      phone: "+1-555-0106", birthday: "1995-07-01", gender: "Female", occupation: "Product Manager",
      language: "en", timezone: "America/New_York", country: "United States",
      website: "https://dianaprince.io", linkedin: "https://linkedin.com/in/dianaprince",
      facebook: "https://facebook.com/dianaprince", twitter: "",
      browser: "Chrome", device: "Desktop",
      contactSource: "website", jobTitle: "VP Product", department: "Product",
      annualIncome: 150000, annualRevenue: 0, customerLifetimeValue: 1200,
      teamSize: 0, nps_score: 9,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_activated", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 5, total_spent: 495, average_order_value: 99,
      first_purchase_date: "2025-03-10T10:00:00Z", last_purchase_date: "2026-01-10T10:00:00Z",
      mrr: 19.99, subscription_activated_date: "2025-03-10T10:00:00Z",
      subscription_created_date: "2025-03-10T10:00:00Z",
      subscription_cancelled_date: "", trial_start_date: "2025-03-01T00:00:00Z",
      trial_end_date: "2025-03-10T00:00:00Z", next_billing_date: "2026-04-10T10:00:00Z",
      lastActivityDate: "2026-03-13T11:00:00Z",
      address: { line1: "321 Park Ave", city: "New York", state: "NY", country: "US", zipcode: "10022" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "edward.norton@example.com", firstName: "Edward", lastName: "Norton",
    tags: '["subscriber"]',
    properties: JSON.stringify({
      phone: "+49-30-123456", birthday: "1985-08-18", gender: "Male", occupation: "Developer",
      language: "de", timezone: "Europe/Berlin", country: "Germany",
      website: "", linkedin: "", facebook: "", twitter: "",
      browser: "Firefox", device: "Desktop",
      contactSource: "api", jobTitle: "Full Stack Developer", department: "Engineering",
      annualIncome: 80000, annualRevenue: 0, customerLifetimeValue: 99,
      teamSize: 0, nps_score: 7,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_installed", plugin_id: "starter-templates",
      plugin_name: "starter-templates", product_name: "Starter Templates",
      platform: "wordpress",
      orders_count: 1, total_spent: 99, average_order_value: 99,
      first_purchase_date: "2025-11-01T10:00:00Z", last_purchase_date: "2025-11-01T10:00:00Z",
      mrr: 0, subscription_activated_date: "", subscription_created_date: "",
      subscription_cancelled_date: "", trial_start_date: "", trial_end_date: "",
      next_billing_date: "", lastActivityDate: "2026-02-28T15:30:00Z",
      address: { line1: "Unter den Linden 77", city: "Berlin", country: "DE", zipcode: "10117" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "fiona.green@example.com", firstName: "Fiona", lastName: "Green",
    tags: '["trial"]',
    properties: JSON.stringify({
      phone: "+61-2-1234-5678", birthday: "1992-12-03", gender: "Female", occupation: "Blogger",
      language: "en", timezone: "Australia/Sydney", country: "Australia",
      website: "https://fionagreen.blog", linkedin: "", facebook: "", twitter: "https://twitter.com/fionagreen",
      browser: "Safari", device: "iPad",
      contactSource: "form", jobTitle: "", department: "",
      annualIncome: 0, annualRevenue: 0, customerLifetimeValue: 0,
      teamSize: 0, nps_score: 0,
      is_marketing_allowed: "true", is_verified: "false",
      email_status: "active", email_verification_status: "pending",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "trial_started", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 0, total_spent: 0, average_order_value: 0,
      first_purchase_date: "", last_purchase_date: "",
      mrr: 0, subscription_activated_date: "",
      subscription_created_date: "", subscription_cancelled_date: "",
      trial_start_date: "2026-03-05T00:00:00Z", trial_end_date: "2026-03-19T00:00:00Z",
      next_billing_date: "", lastActivityDate: "2026-03-14T02:00:00Z",
      address: { line1: "42 Harbour Rd", city: "Sydney", state: "NSW", country: "AU", zipcode: "2000" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "george.harris@example.com", firstName: "George", lastName: "Harris",
    tags: '["subscriber","premium"]',
    properties: JSON.stringify({
      phone: "+1-555-0109", birthday: "1978-06-25", gender: "Male", occupation: "Agency Owner",
      language: "en", timezone: "America/New_York", country: "United States",
      website: "https://harrisagency.com", linkedin: "https://linkedin.com/in/georgeharris",
      facebook: "", twitter: "",
      browser: "Chrome", device: "Desktop",
      contactSource: "website", jobTitle: "Founder & CEO", department: "",
      annualIncome: 250000, annualRevenue: 1500000, customerLifetimeValue: 3500,
      teamSize: 25, nps_score: 10,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_activated", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 8, total_spent: 792, average_order_value: 99,
      first_purchase_date: "2025-02-01T10:00:00Z", last_purchase_date: "2026-01-01T10:00:00Z",
      mrr: 49.99, subscription_activated_date: "2025-02-01T10:00:00Z",
      subscription_created_date: "2025-02-01T10:00:00Z",
      subscription_cancelled_date: "", trial_start_date: "",
      trial_end_date: "", next_billing_date: "2026-04-01T10:00:00Z",
      lastActivityDate: "2026-03-11T10:00:00Z",
      address: { line1: "555 Madison Ave", city: "New York", state: "NY", country: "US", zipcode: "10022" },
      uninstall_feedback: "temporary", feedback_text: "Will reinstall later",
      feed: "", uninstall_reason_id: "reason_01",
    }),
  },
  {
    email: "hannah.clark@example.com", firstName: "Hannah", lastName: "Clark",
    tags: '["lead","subscriber"]',
    properties: JSON.stringify({
      phone: "+1-555-0110", birthday: "1993-09-14", gender: "Female", occupation: "Content Creator",
      language: "en", timezone: "America/Los_Angeles", country: "United States",
      website: "https://hannahclark.co", linkedin: "", facebook: "https://facebook.com/hannahclark", twitter: "",
      browser: "Chrome", device: "Mobile",
      contactSource: "api", jobTitle: "Content Strategist", department: "Marketing",
      annualIncome: 75000, annualRevenue: 0, customerLifetimeValue: 149,
      teamSize: 0, nps_score: 8,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_installed", plugin_id: "starter-templates",
      plugin_name: "starter-templates", product_name: "Starter Templates",
      platform: "wordpress",
      orders_count: 2, total_spent: 149, average_order_value: 74.5,
      first_purchase_date: "2025-08-20T10:00:00Z", last_purchase_date: "2025-12-20T10:00:00Z",
      mrr: 0, subscription_activated_date: "", subscription_created_date: "",
      subscription_cancelled_date: "", trial_start_date: "", trial_end_date: "",
      next_billing_date: "", lastActivityDate: "2026-03-09T18:00:00Z",
      address: { line1: "890 Sunset Blvd", city: "Los Angeles", state: "CA", country: "US", zipcode: "90028" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "ivan.petrov@example.com", firstName: "Ivan", lastName: "Petrov",
    tags: '["subscriber"]',
    properties: JSON.stringify({
      phone: "+7-495-123-4567", birthday: "1987-01-30", gender: "Male", occupation: "Sysadmin",
      language: "ru", timezone: "Europe/Moscow", country: "Russia",
      website: "", linkedin: "", facebook: "", twitter: "",
      browser: "Chrome", device: "Desktop",
      contactSource: "import", jobTitle: "System Administrator", department: "IT",
      annualIncome: 60000, annualRevenue: 0, customerLifetimeValue: 49,
      teamSize: 0, nps_score: 6,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_installed", plugin_id: "starter-templates",
      plugin_name: "starter-templates", product_name: "Starter Templates",
      platform: "wordpress",
      orders_count: 1, total_spent: 49, average_order_value: 49,
      first_purchase_date: "2025-10-05T10:00:00Z", last_purchase_date: "2025-10-05T10:00:00Z",
      mrr: 0, subscription_activated_date: "", subscription_created_date: "",
      subscription_cancelled_date: "", trial_start_date: "", trial_end_date: "",
      next_billing_date: "", lastActivityDate: "2026-02-20T07:00:00Z",
      address: { line1: "Tverskaya 15", city: "Moscow", country: "RU", zipcode: "125009" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "julia.martinez@example.com", firstName: "Julia", lastName: "Martinez",
    tags: '["premium","enterprise"]',
    properties: JSON.stringify({
      phone: "+34-91-123-4567", birthday: "1980-04-12", gender: "Female", occupation: "Director",
      language: "es", timezone: "Europe/Madrid", country: "Spain",
      website: "https://martinez-corp.es", linkedin: "https://linkedin.com/in/juliamartinez",
      facebook: "", twitter: "",
      browser: "Chrome", device: "Desktop",
      contactSource: "website", jobTitle: "Director of Operations", department: "Operations",
      annualIncome: 130000, annualRevenue: 5000000, customerLifetimeValue: 5000,
      teamSize: 100, nps_score: 9,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_activated", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 20, total_spent: 5000, average_order_value: 250,
      first_purchase_date: "2025-01-01T10:00:00Z", last_purchase_date: "2026-03-01T10:00:00Z",
      mrr: 249, subscription_activated_date: "2025-01-01T10:00:00Z",
      subscription_created_date: "2025-01-01T10:00:00Z",
      subscription_cancelled_date: "", trial_start_date: "",
      trial_end_date: "", next_billing_date: "2026-04-01T10:00:00Z",
      lastActivityDate: "2026-03-14T14:00:00Z",
      address: { line1: "Gran Via 28", city: "Madrid", country: "ES", zipcode: "28013" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "kevin.lee@example.com", firstName: "Kevin", lastName: "Lee",
    tags: '["trial"]',
    properties: JSON.stringify({
      phone: "+82-2-1234-5678", birthday: "1996-10-10", gender: "Male", occupation: "Student",
      language: "ko", timezone: "Asia/Seoul", country: "South Korea",
      website: "", linkedin: "", facebook: "", twitter: "",
      browser: "Chrome", device: "Laptop",
      contactSource: "form", jobTitle: "", department: "",
      annualIncome: 0, annualRevenue: 0, customerLifetimeValue: 0,
      teamSize: 0, nps_score: 0,
      is_marketing_allowed: "false", is_verified: "false",
      email_status: "active", email_verification_status: "unknown",
      marketing_email_subscription_status: "unsubscribed", marketing_contact_status: "non_marketing_contact",
      event_type: "trial_started", plugin_id: "starter-templates",
      plugin_name: "starter-templates", product_name: "Starter Templates",
      platform: "wordpress",
      orders_count: 0, total_spent: 0, average_order_value: 0,
      first_purchase_date: "", last_purchase_date: "",
      mrr: 0, subscription_activated_date: "", subscription_created_date: "",
      subscription_cancelled_date: "", trial_start_date: "2026-03-10T00:00:00Z",
      trial_end_date: "2026-03-24T00:00:00Z",
      next_billing_date: "", lastActivityDate: "2026-03-13T06:00:00Z",
      address: { line1: "Gangnam-gu", city: "Seoul", country: "KR", zipcode: "06000" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "laura.wilson@example.com", firstName: "Laura", lastName: "Wilson",
    tags: '["subscriber","early-adopter"]',
    properties: JSON.stringify({
      phone: "+1-555-0114", birthday: "1991-02-28", gender: "Female", occupation: "Marketer",
      language: "en", timezone: "America/New_York", country: "United States",
      website: "https://laurawilson.com", linkedin: "https://linkedin.com/in/laurawilson",
      facebook: "", twitter: "https://twitter.com/lauraw",
      browser: "Safari", device: "MacBook",
      contactSource: "website", jobTitle: "Head of Growth", department: "Marketing",
      annualIncome: 110000, annualRevenue: 0, customerLifetimeValue: 800,
      teamSize: 0, nps_score: 9,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_activated", plugin_id: "starter-templates-pro",
      plugin_name: "starter-templates", product_name: "Starter Templates Pro",
      platform: "wordpress",
      orders_count: 4, total_spent: 396, average_order_value: 99,
      first_purchase_date: "2025-04-01T10:00:00Z", last_purchase_date: "2026-01-15T10:00:00Z",
      mrr: 9.99, subscription_activated_date: "2025-04-01T10:00:00Z",
      subscription_created_date: "2025-04-01T10:00:00Z",
      subscription_cancelled_date: "", trial_start_date: "2025-03-25T00:00:00Z",
      trial_end_date: "2025-04-01T00:00:00Z", next_billing_date: "2026-04-15T10:00:00Z",
      lastActivityDate: "2026-03-12T20:00:00Z",
      address: { line1: "200 W 57th St", city: "New York", state: "NY", country: "US", zipcode: "10019" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
  {
    email: "mike.taylor@example.com", firstName: "Mike", lastName: "Taylor",
    tags: '["subscriber"]',
    properties: JSON.stringify({
      phone: "+44-7700-900123", birthday: "1983-07-19", gender: "Male", occupation: "Consultant",
      language: "en", timezone: "Europe/London", country: "United Kingdom",
      website: "https://miketaylor.co.uk", linkedin: "", facebook: "", twitter: "",
      browser: "Chrome", device: "Desktop",
      contactSource: "api", jobTitle: "Senior Consultant", department: "Advisory",
      annualIncome: 90000, annualRevenue: 0, customerLifetimeValue: 297,
      teamSize: 0, nps_score: 7,
      is_marketing_allowed: "true", is_verified: "true",
      email_status: "active", email_verification_status: "valid",
      marketing_email_subscription_status: "subscribed", marketing_contact_status: "marketing_contact",
      event_type: "plugin_installed", plugin_id: "starter-templates",
      plugin_name: "starter-templates", product_name: "Starter Templates",
      platform: "wordpress",
      orders_count: 3, total_spent: 297, average_order_value: 99,
      first_purchase_date: "2025-05-10T10:00:00Z", last_purchase_date: "2025-12-10T10:00:00Z",
      mrr: 0, subscription_activated_date: "", subscription_created_date: "",
      subscription_cancelled_date: "", trial_start_date: "", trial_end_date: "",
      next_billing_date: "", lastActivityDate: "2026-03-10T16:30:00Z",
      address: { line1: "50 Oxford St", city: "London", country: "UK", zipcode: "W1D 1BS" },
      uninstall_feedback: "", feedback_text: "", feed: "", uninstall_reason_id: "",
    }),
  },
];

async function main() {
  console.log("Seeding contacts...");

  // Clear existing contacts
  await prisma.contact.deleteMany();

  for (const contact of dummyContacts) {
    await prisma.contact.create({
      data: {
        email: contact.email,
        firstName: contact.firstName,
        lastName: contact.lastName,
        fullName: `${contact.firstName} ${contact.lastName}`,
        tags: contact.tags,
        properties: contact.properties,
      },
    });
  }

  console.log(`Seeded ${dummyContacts.length} contacts.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
